"""initial_migration

Revision ID: 2efde82c040b
Revises: 
Create Date: 2026-05-11 23:33:25.196019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2efde82c040b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_department'), 'users', ['department'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_role_is_active', 'users', ['role', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('meetings',
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('audio_file_path', sa.String(length=1000), nullable=True),
    sa.Column('audio_duration', sa.Integer(), nullable=True, comment='Sekundda audio davomiyligi'),
    sa.Column('transcript', sa.Text(), nullable=True, comment='Whisper STT natijasi'),
    sa.Column('edited_transcript', sa.Text(), nullable=True, comment='Secretary tomonidan tahrirlangan matn'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='processing|ready|distributing|distributed|confirmed|failed'),
    sa.Column('meeting_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_created_by'), 'meetings', ['created_by'], unique=False)
    op.create_index(op.f('ix_meetings_meeting_date'), 'meetings', ['meeting_date'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=20), nullable=False, comment='task | payment | debt | general'),
    sa.Column('priority', sa.String(length=10), nullable=False, comment='high | medium | low'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | confirmed | in_progress | submitted | approved | rejected'),
    sa.Column('deadline', sa.DateTime(), nullable=True, comment='Topshiriq muddati'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True, comment="To'lov yoki qarz miqdori"),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='UZS | USD | EUR'),
    sa.Column('is_edited', sa.Boolean(), nullable=False, comment='Secretary tomonidan tahrirlangan'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='Transcript dagi tartib raqami'),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_assigned_status', 'tasks', ['assigned_to', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_deadline'), 'tasks', ['deadline'], unique=False)
    op.create_index('ix_tasks_deadline_status', 'tasks', ['deadline', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_meeting_id'), 'tasks', ['meeting_id'], unique=False)
    op.create_index('ix_tasks_meeting_status', 'tasks', ['meeting_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_table('task_reports',
    sa.Column('report_text', sa.Text(), nullable=True, comment='Xodim yozgan matnli hisobot'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='submitted | approved | rejected'),
    sa.Column('rejection_note', sa.Text(), nullable=True, comment='Rad etilsa sababi'),
    sa.Column('submitted_at', sa.DateTime(), nullable=False, comment='Hisobot yuborilgan vaqt'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment="Ko'rib chiqilgan vaqt"),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_reports_employee_id'), 'task_reports', ['employee_id'], unique=False)
    op.create_index('ix_task_reports_employee_status', 'task_reports', ['employee_id', 'status'], unique=False)
    op.create_index(op.f('ix_task_reports_status'), 'task_reports', ['status'], unique=False)
    op.create_index(op.f('ix_task_reports_submitted_at'), 'task_reports', ['submitted_at'], unique=False)
    op.create_index('ix_task_reports_task_employee', 'task_reports', ['task_id', 'employee_id'], unique=False)
    op.create_index(op.f('ix_task_reports_task_id'), 'task_reports', ['task_id'], unique=True)
    op.create_table('report_attachments',
    sa.Column('file_path', sa.String(length=1000), nullable=False, comment="Serverda saqlangan fayl yo'li"),
    sa.Column('file_name', sa.String(length=500), nullable=False, comment='Asl fayl nomi'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='Fayl hajmi — byte'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='image | video | document | audio'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='image/jpeg, video/mp4 kabi MIME turi'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False, comment='Fayl yuklangan vaqt'),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['task_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_attachments_file_type'), 'report_attachments', ['file_type'], unique=False)
    op.create_index(op.f('ix_report_attachments_report_id'), 'report_attachments', ['report_id'], unique=False)
    op.create_index('ix_report_attachments_report_type', 'report_attachments', ['report_id', 'file_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_report_attachments_report_type', table_name='report_attachments')
    op.drop_index(op.f('ix_report_attachments_report_id'), table_name='report_attachments')
    op.drop_index(op.f('ix_report_attachments_file_type'), table_name='report_attachments')
    op.drop_table('report_attachments')
    op.drop_index(op.f('ix_task_reports_task_id'), table_name='task_reports')
    op.drop_index('ix_task_reports_task_employee', table_name='task_reports')
    op.drop_index(op.f('ix_task_reports_submitted_at'), table_name='task_reports')
    op.drop_index(op.f('ix_task_reports_status'), table_name='task_reports')
    op.drop_index('ix_task_reports_employee_status', table_name='task_reports')
    op.drop_index(op.f('ix_task_reports_employee_id'), table_name='task_reports')
    op.drop_table('task_reports')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index('ix_tasks_meeting_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_meeting_id'), table_name='tasks')
    op.drop_index('ix_tasks_deadline_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_deadline'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_index('ix_tasks_assigned_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_date'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_created_by'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_role_is_active', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_department'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
